<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-RMVDHMS" failures="1" tests="3" name="Error Validations Test" time="26.474" errors="0" timestamp="2024-09-30T23:00:54 IST">
  <testcase classname="hcyclewala.tests.ErrorValidationsTest" name="LoginErrorValidation" time="3.145">
    <skipped/>
  </testcase> <!-- LoginErrorValidation -->
  <testcase classname="hcyclewala.tests.ErrorValidationsTest" name="LoginErrorValidation" time="1.067">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at hcyclewala.tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- LoginErrorValidation -->
  <testcase classname="hcyclewala.tests.ErrorValidationsTest" name="ProductErrorValidation" time="3.215"/>
</testsuite> <!-- Error Validations Test -->
